name: Tico
favicon: null
layout_spectrum: 0.14626100938767195
typography_spectrum: 0.5436883601360023
title: ticowear
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003556'
    - '#3f3f3f'
    - '#7590a0'
    - '#7a7a7a'
  brandStrength: 0.25
  lightness: 0.5299857154022902
  saturation: 0.6156815933063626
  rhythmicContrast: 0.4114038930274546
purpose: []
