name: Tico
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27779
title: ticowear
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003556'
    - '#3f3f3f'
    - '#7590a0'
    - '#7a7a7a'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
