name: Tico
favicon: null
layout_spectrum: 0.14626100938767195
typography_spectrum: 0.5436883601360023
title: ticowear
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8134753077756613
  lightness: 0.5299857154022902
  saturation: 0.6156815933063626
  rhythmicContrast: 0.4114038930274546
purpose: []
